version: '3'
services:
    mongo:
        image: mongo:3.2
        ports:
            - 27018:27017
        networks:
            main:
        volumes:
            - ./charging-data:/data/db

    charging:
        image: charging-p3
        links:
            - mongo
        depends_on:
            - mongo
        ports:
            - 8006:8006
        networks:
            main:
                aliases:
                    - charging.docker
        volumes:
            - ../src:/business-ecosystem-charging-backend/src/

networks:
    main:
        external: true
